# Gradient test

### RBF kernel

In [2]:
import numpy
import GPy
N, Q = 10, 3
X = numpy.random.randn(N-5,Q)
print(X)

[[-0.44911852  0.53789662  1.23012424]
 [-0.5555795  -1.05571552 -1.83853259]
 [ 1.18123204  0.22285161 -1.69385651]
 [-0.81275225 -0.83291592 -0.78837615]
 [-1.11158247 -0.58022931 -0.65935282]]


In [3]:
kern = GPy.kern.RBF(Q, ARD=True)
print(kern.K(X))

[[ 1.          0.00251925  0.0035053   0.04769875  0.07210774]
 [ 0.00251925  1.          0.09670505  0.54372971  0.38180484]
 [ 0.0035053   0.09670505  1.          0.0520653   0.03062105]
 [ 0.04769875  0.54372971  0.0520653   1.          0.9186055 ]
 [ 0.07210774  0.38180484  0.03062105  0.9186055   1.        ]]


In [4]:
grad = GPy.kern.RBF(Q, ARD=True).gradients_X(numpy.ones((1,1)), X)
print(grad)

[[-0.11933398 -0.30226122 -0.501012  ]
 [-0.3677809   0.86068859  2.08587884]
 [-0.69539817 -0.40419921  0.15016043]
 [-0.02702472  0.46266287 -0.80668776]
 [ 1.20953777 -0.61689104 -0.9283395 ]]


In [5]:
check = GPy.models.GradientChecker(kern.K,lambda x: grad,x0 = X.copy())
check.checkgrad(verbose=1)

            Name             |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio    
-------------------------------------------------------------------------------------------------------------
 GradientChecker.X[[0 0]]    |   1.000000    |   0.000000    |   0.119334    |   0.119334    |     3e-08     
 GradientChecker.X[[0 1]]    |   1.000000    |   0.000000    |   0.302261    |   0.302261    |     7e-08     
 GradientChecker.X[[0 2]]    |   1.000000    |   0.000000    |   0.501012    |   0.501012    |     1e-07     
 GradientChecker.X[[1 0]]    |   1.000000    |   0.000000    |   0.367781    |   0.367781    |     8e-08     
 GradientChecker.X[[1 1]]    |   1.000000    |   0.000000    |   -0.860689   |   -0.860689   |     2e-07     
 GradientChecker.X[[1 2]]    |   1.000000    |   0.000000    |   -2.085879   |   -2.085879   |     4e-07     
 GradientChecker.X[[2 0]]    |   1.000000    |   0.000000    |   0.695398    |   0.695398    |     1e-07     
 GradientC

True

In [62]:
# Compute gradient Kx and check or check might be it is what we need (check dimensionality)

### Linear kernel

In [6]:
N, Q = 10, 3
X = numpy.random.randn(N-5,Q)
print(X)

[[ 1.54683373 -0.14977037 -0.46239145]
 [ 1.06526514 -1.09362411 -0.01371721]
 [ 0.03390794 -1.27371788 -0.77556329]
 [ 0.15126075 -1.0425393   1.07597133]
 [-0.1135123   1.07793879  0.77555985]]


In [70]:
kern = GPy.kern.Linear(Q, ARD=True)
print(kern.K(X))

[[ 0.7548939   1.03731917 -0.50719281 -0.42277545 -0.32074292]
 [ 1.03731917  3.20063495 -2.49518877 -0.33834905 -0.74495527]
 [-0.50719281 -2.49518877  2.23112159 -0.16880548  0.43420397]
 [-0.42277545 -0.33834905 -0.16880548  0.89343806  0.40735212]
 [-0.32074292 -0.74495527  0.43420397  0.40735212  0.30471888]]


In [71]:
grad = kern.gradients_X(numpy.ones((5,5)), X)
print(grad)

[[-0.06417783 -1.47884617  1.54759456]
 [-0.06417783 -1.47884617  1.54759456]
 [-0.06417783 -1.47884617  1.54759456]
 [-0.06417783 -1.47884617  1.54759456]
 [-0.06417783 -1.47884617  1.54759456]]


In [22]:
check = GPy.models.GradientChecker(kern.K,lambda x: grad,x0 = X.copy())
check.checkgrad(verbose=1)

            Name             |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio    
-------------------------------------------------------------------------------------------------------------
 GradientChecker.X[[0 0]]    |   1.000000    |   0.000000    |   -5.367511   |   -5.367511   |     8e-07     
 GradientChecker.X[[0 1]]    |   1.000000    |   0.000000    |   4.963426    |   4.963426    |     7e-07     
 GradientChecker.X[[0 2]]    |   1.000000    |   0.000000    |   -1.199718   |   -1.199718   |     2e-07     
 GradientChecker.X[[1 0]]    |   1.000000    |   0.000000    |   -5.367511   |   -5.367511   |     8e-07     
 GradientChecker.X[[1 1]]    |   1.000000    |   0.000000    |   4.963426    |   4.963426    |     7e-07     
 GradientChecker.X[[1 2]]    |   1.000000    |   0.000000    |   -1.199718   |   -1.199718   |     2e-07     
 GradientChecker.X[[2 0]]    |   1.000000    |   0.000000    |   -5.367511   |   -5.367511   |     8e-07     
 GradientC

True

### Kx

In [30]:
N, Q = 10, 3
X = numpy.random.randn(N-5,Q)
print(X)

[[-0.24688349 -0.82693093 -0.10063637]
 [ 0.8992477  -1.46122037 -0.50677763]
 [-1.15031156  0.93357093  0.19065737]
 [ 0.49306098  0.27164739  0.75930009]
 [-0.02720254  0.3435099   0.43125381]]


In [56]:
kern1 = GPy.kern.Linear(Q, ARD=True)
print(kern1.K(X))

[[ 0.7548939   1.03731917 -0.50719281 -0.42277545 -0.32074292]
 [ 1.03731917  3.20063495 -2.49518877 -0.33834905 -0.74495527]
 [-0.50719281 -2.49518877  2.23112159 -0.16880548  0.43420397]
 [-0.42277545 -0.33834905 -0.16880548  0.89343806  0.40735212]
 [-0.32074292 -0.74495527  0.43420397  0.40735212  0.30471888]]


In [75]:
grad1 = kern1.gradients_X(numpy.ones((5,5)), X)
print(grad)

[[-0.06417783 -1.47884617  1.54759456]
 [-0.06417783 -1.47884617  1.54759456]
 [-0.06417783 -1.47884617  1.54759456]
 [-0.06417783 -1.47884617  1.54759456]
 [-0.06417783 -1.47884617  1.54759456]]


In [77]:
kern2 = GPy.kern.RBF(Q, ARD=True)
print(kern2.K(X))

[[ 1.          0.39045395  0.13530814  0.28738243  0.42718021]
 [ 0.39045395  1.          0.00545585  0.09205348  0.08227959]
 [ 0.13530814  0.00545585  1.          0.17709211  0.43443182]
 [ 0.28738243  0.09205348  0.17709211  1.          0.82553274]
 [ 0.42718021  0.08227959  0.43443182  0.82553274  1.        ]]


In [82]:
grad2 = kern2.gradients_X(numpy.ones((5,5)), X)
print(grad2)

[[ 1.26352133  1.6125014   0.71035711]
 [-1.14462475  1.13747082  0.71222452]
 [ 1.82473172 -1.24967715  0.32401074]
 [-1.79155803 -0.59736467 -1.47038514]
 [-0.15207026 -0.9029304  -0.27620723]]


In [95]:
kern3 = GPy.kern.Poly(Q)
print(kern3.K(X))

[[  5.40446355e+00   8.45623836e+00   1.19682626e-01   1.92324400e-01
    3.13402545e-01]
 [  8.45623836e+00   7.41216068e+01  -3.34262822e+00   2.89658868e-01
    1.65901023e-02]
 [  1.19682626e-01  -3.34262822e+00   3.37333836e+01   5.74259268e-01
    2.95007299e+00]
 [  1.92324400e-01   2.89658868e-01   5.74259268e-01   6.78817935e+00
    2.78745787e+00]
 [  3.13402545e-01   1.65901023e-02   2.95007299e+00   2.78745787e+00
    2.22101168e+00]]


In [94]:
grad3 = kern3.gradients_X(numpy.ones((1,1)), X)
print(grad3)

NotImplementedError: 

In [60]:
kern4 = GPy.kern.RatQuad(Q, ARD=True)
print(kern4.K(X))

[[ 1.          0.26558113  0.11109626  0.19806899  0.29201064]
 [ 0.26558113  1.          0.02592194  0.08725367  0.08174322]
 [ 0.11109626  0.02592194  1.          0.13406934  0.29739641]
 [ 0.19806899  0.08725367  0.13406934  1.          0.70412038]
 [ 0.29201064  0.08174322  0.29739641  0.70412038  1.        ]]


In [86]:
grad4 = kern4.gradients_X(numpy.ones((5,5)), X)
print(grad4)

[[ 0.89321718  1.03963981  0.45973556]
 [-0.79016528  0.73459225  0.45220751]
 [ 1.21931711 -0.81350711  0.21295199]
 [-1.77129511 -0.26619723 -1.32069225]
 [ 0.4489261  -0.69452772  0.19579719]]


In [61]:
kern5 = GPy.kern.MLP(Q, ARD=True)
print(kern5.K(X))

[[ 0.43965771  0.36182352  0.09221397  0.13108059  0.17376361]
 [ 0.36182352  0.59859282 -0.2065211   0.10911952  0.04694106]
 [ 0.09221397 -0.2065211   0.55319529  0.1526933   0.30378254]
 [ 0.13108059  0.10911952  0.1526933   0.45414936  0.36693136]
 [ 0.17376361  0.04694106  0.30378254  0.36693136  0.38310267]]


In [87]:
grad5 = kern5.gradients_X(numpy.ones((5,5)), X)
print(grad5)

[[ 0.22982488  0.38070156  0.48301039]
 [-0.32287145  0.23430032  0.45408509]
 [ 0.40768952 -0.52827867  0.28757685]
 [-0.43891441 -0.41393517 -0.16395209]
 [-0.0210358  -0.57322974  0.05740467]]


In [62]:
kern6 = GPy.kern.Matern52(Q, ARD=True)
print(kern6.K(X))

[[ 1.          0.33541703  0.13863933  0.25428485  0.36544446]
 [ 0.33541703  1.          0.0187491   0.1046833   0.09673694]
 [ 0.13863933  0.0187491   1.          0.17049723  0.37145623]
 [ 0.25428485  0.1046833   0.17049723  1.          0.75717706]
 [ 0.36544446  0.09673694  0.37145623  0.75717706  1.        ]]


In [88]:
grad6 = kern6.gradients_X(numpy.ones((5,5)), X)
print(grad6)

[[ 1.01777561  1.27900198  0.56026945]
 [-0.95014131  0.94938544  0.58497045]
 [ 1.48119356 -1.01846033  0.25160867]
 [-1.74335235 -0.42218809 -1.37360025]
 [ 0.19452448 -0.787739   -0.02324833]]


In [110]:
kern = kern1 + kern2 + kern4 + kern5 + kern6# + kern3
print(kern.K(X))

[[ 4.19455161  2.3905948  -0.02993511  0.44804143  0.937656  ]
 [ 2.3905948   6.79922778 -2.65158297  0.05476092 -0.43725446]
 [-0.02993511 -2.65158297  5.78431688  0.46554649  1.84127098]
 [ 0.44804143  0.05476092  0.46554649  4.34758742  3.06111366]
 [ 0.937656   -0.43725446  1.84127098  3.06111366  3.68782156]]


In [103]:
grad = kern.gradients_X(numpy.ones((5,5)), X)
print(grad)

[[ 3.34016117  2.83299857  3.76096708]
 [-3.27198062  1.57690266  3.75108214]
 [ 4.86875409 -5.08876942  2.62374281]
 [-5.80929772 -3.17853132 -2.78103517]
 [ 0.40616669 -4.43727304  1.50134087]]


In [107]:
check = GPy.models.GradientChecker(kern.K,lambda x: grad,x0 = X.copy())
check.checkgrad(verbose=1)

            Name             |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio    
-------------------------------------------------------------------------------------------------------------
 GradientChecker.X[[0 0]]    |   1.000000    |   0.000000    |   -3.340161   |   -3.340161   |     2e-07     
 GradientChecker.X[[0 1]]    |   1.000000    |   0.000000    |   -2.832999   |   -2.832999   |     2e-07     
 GradientChecker.X[[0 2]]    |   1.000000    |   0.000000    |   -3.760967   |   -3.760967   |     2e-07     
 GradientChecker.X[[1 0]]    |   1.000000    |   0.000000    |   3.271981    |   3.271981    |     2e-07     
 GradientChecker.X[[1 1]]    |   1.000000    |   0.000000    |   -1.576903   |   -1.576903   |     9e-08     
 GradientChecker.X[[1 2]]    |   1.000000    |   0.000000    |   -3.751082   |   -3.751082   |     2e-07     
 GradientChecker.X[[2 0]]    |   1.000000    |   0.000000    |   -4.868754   |   -4.868754   |     3e-07     
 GradientC

True

Using lambda function notation:

In [114]:
check = GPy.models.GradientChecker(lambda X: kern.K(X),lambda x: grad,x0 = X.copy())
check.checkgrad(verbose=1)

            Name             |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio    
-------------------------------------------------------------------------------------------------------------
 GradientChecker.X[[0 0]]    |   1.000000    |   0.000000    |   -3.340161   |   -3.340161   |     2e-07     
 GradientChecker.X[[0 1]]    |   1.000000    |   0.000000    |   -2.832999   |   -2.832999   |     2e-07     
 GradientChecker.X[[0 2]]    |   1.000000    |   0.000000    |   -3.760967   |   -3.760967   |     2e-07     
 GradientChecker.X[[1 0]]    |   1.000000    |   0.000000    |   3.271981    |   3.271981    |     2e-07     
 GradientChecker.X[[1 1]]    |   1.000000    |   0.000000    |   -1.576903   |   -1.576903   |     9e-08     
 GradientChecker.X[[1 2]]    |   1.000000    |   0.000000    |   -3.751082   |   -3.751082   |     2e-07     
 GradientChecker.X[[2 0]]    |   1.000000    |   0.000000    |   -4.868754   |   -4.868754   |     3e-07     
 GradientC

True