# Gradient test

In [41]:
import numpy
import GPy
N, Q = 10, 3
X = numpy.random.randn(N,Q)
print(X)

[[-0.03967998  0.50290002  0.39887573]
 [ 0.39579102 -0.0366513  -1.16380394]
 [ 0.04327608  0.98871395  0.43881007]
 [ 0.21369124  0.3334702   0.02060364]
 [-1.27292457 -1.44405822  1.28196086]
 [ 1.0792803   0.40035224 -0.18843778]
 [ 2.13830035 -0.08451158  0.27270048]
 [ 0.68117581  0.55878812  0.72716744]
 [-1.49267315  0.49093952 -0.36139139]
 [ 1.2030623   1.11778862 -0.92417162]]


In [48]:
kern = GPy.kern.RBF(Q, ARD=True)
print(kern.K(X))

[[  1.00000000e+00   2.31920838e-01   8.84930809e-01   8.88699069e-01
    4.75635308e-02   4.47641471e-01   7.79034186e-02   7.29594779e-01
    2.60625918e-01   1.59378193e-01]
 [  2.31920838e-01   1.00000000e+00   1.53814774e-01   4.55442509e-01
    4.63747291e-03   4.47206681e-01   7.79968252e-02   1.34541487e-01
    1.06006226e-01   3.60262968e-01]
 [  8.84930809e-01   1.53814774e-01   1.00000000e+00   7.28592157e-01
    1.52857551e-02   4.03952874e-01   6.17744108e-02   7.13586846e-01
    1.97183422e-01   1.99939249e-01]
 [  8.88699069e-01   4.55442509e-01   7.28592157e-01   1.00000000e+00
    3.07973100e-02   6.71186678e-01   1.39290875e-01   6.80946731e-01
    2.14124401e-01   2.88429270e-01]
 [  4.75635308e-02   4.63747291e-03   1.52857551e-02   3.07973100e-02
    1.00000000e+00   3.89370194e-03   7.08957827e-04   1.70970604e-02
    3.89079706e-02   1.53732673e-04]
 [  4.47641471e-01   4.47206681e-01   4.03952874e-01   6.71186678e-01
    3.89370194e-03   1.00000000e+00   4.56287

In [59]:
grad = GPy.kern.RBF(Q, ARD=True).gradients_X(numpy.ones((1,1)), X)
print(grad)

[[ 2.71358912  0.21118894 -2.12694385]
 [ 0.64943369  2.37706178  4.26746788]
 [ 2.0339827  -3.57064748 -2.12366083]
 [ 1.55038408  1.60940525  0.32386962]
 [ 0.33823244  0.61825956 -0.37056846]
 [-3.18145138  0.66607215  1.09801146]
 [-3.41000132  1.48427534 -0.81077588]
 [-1.55222495 -0.31358136 -4.41547407]
 [ 3.02873133 -0.10464599  0.93906994]
 [-2.17067571 -2.97738818  3.2190042 ]]


In [60]:
check = GPy.models.GradientChecker(kern.K,lambda x: grad,x0 = X.copy())
check.checkgrad(verbose=1)

            Name             |     Ratio     |  Difference   |  Analytical   |   Numerical   |   dF_ratio    
-------------------------------------------------------------------------------------------------------------
 GradientChecker.X[[0 0]]    |   1.000000    |   0.000000    |   -2.713589   |   -2.713589   |     2e-07     
 GradientChecker.X[[0 1]]    |   1.000000    |   0.000000    |   -0.211189   |   -0.211189   |     1e-08     
 GradientChecker.X[[0 2]]    |   1.000000    |   0.000000    |   2.126944    |   2.126944    |     1e-07     
 GradientChecker.X[[1 0]]    |   1.000000    |   0.000000    |   -0.649434   |   -0.649434   |     4e-08     
 GradientChecker.X[[1 1]]    |   1.000000    |   0.000000    |   -2.377062   |   -2.377062   |     1e-07     
 GradientChecker.X[[1 2]]    |   1.000000    |   0.000000    |   -4.267468   |   -4.267468   |     2e-07     
 GradientChecker.X[[2 0]]    |   1.000000    |   0.000000    |   -2.033983   |   -2.033983   |     1e-07     
 GradientC

True

In [62]:
# Compute gradient Kx and check or check might be it is what we need (check dimensionality)